FROM node:18-alpine

WORKDIR /ft_transcendence-nextjs

# COPY ./package.json ./
# COPY ./yarn.lock ./

# RUN npm install yarn
# RUN yarn install

# COPY ./ ./

# RUN yarn build

# CMD ["yarn", "start"]

# potential fix for heap out of memory
# ENV NODE_OPTIONS=--max_old_space_size=2048

CMD ["yarn", "dev"]