import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  name: 'viewport',
  content: 'initial-scale=1, width=device-width',
};

// MUI recommended meta tag, not sure if above way works
// <meta name='viewport' content='initial-scale=1, width=device-width' />;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
