version: "3"

services:
    nestjs:
      container_name: backend
      build: ./backend
      image: backend-nestjs
      depends_on:
        - postgres
      restart: on-failure
      volumes:
        - ./backend:/ft_transcendence-nestjs
      ports:
        - "3000:3000"
    postgres:
        container_name: database
        image: postgres:15-alpine
        restart: on-failure
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        expose:
          - "5432"
