export enum View {
  EMPTY = 'EMPTY',
  GAME = 'GAME',
  CHAT = 'CHAT',
  PROFILE = 'PROFILE',
  LEADERBOARD = 'LEADERBOARD',
  ACHIEVEMENTS = 'ACHIEVEMENTS',
  ABOUT_US = 'ABOUT_US',
  SETTINGS = 'SETTINGS',
}

export enum SocialTab {
  FRIEND = 'FRIEND',
  CHANNEL = 'CHANNEL',
}
